-- Service Operations

SHOW ENDPOINTS IN SERVICE R_SPCS_DB.PUBLIC.RSTUDIO_SERVICE;

-- Suspend (save costs)
ALTER SERVICE R_SPCS_DB.PUBLIC.RSTUDIO_SERVICE SUSPEND;
ALTER COMPUTE POOL RSTUDIO_POOL SUSPEND;

-- Resume
ALTER COMPUTE POOL RSTUDIO_POOL RESUME;
ALTER SERVICE R_SPCS_DB.PUBLIC.RSTUDIO_SERVICE RESUME;
